#!/usr/bin/env ruby
require 'bundler/setup'
Bundler.require(:default)
$:.unshift(File.expand_path(File.join(__dir__, '../lib')))
require 'vemu'
# require 'debug'

require 'open3'
# puts OS.report

vm = Vemu::VM.new('early')
vm.cpus = 1
vm.memory = '768'
vm.cloud_init.add_user(:lime,
  sudoer: true,
  ssh_keys: File.read(File.join(ENV['HOME'], '.ssh/id_ed25519_vemu_temp.pub'))
)
# vm.add_tap_netdev('eth0', mac: '52:55:55:c2:d9:ac', host_tap: 'tap0')

vm.add_user_netdev('eth0', mac: '52:55:55:c2:d9:af')
vm.vsock_cid = 10015050
vm.vsock_mode = :user

vm.cloud_init.append_user_data_hook do |ci_data|
  ci_data[:write_files] ||= []
  ci_data[:runcmd] ||= []

  ci_data[:runcmd] += [
    ['systemctl', 'daemon-reload'],
    ['systemctl', 'enable', '--now', 'sshd-vsock.socket'],
  ]

  ci_data[:write_files] << {
    path: '/etc/systemd/system/sshd-vsock.socket',
    permissions: '0644',
    content: <<~SYSTEMD_UNIT
      [Unit]
      Description=OpenSSH over AF_VSOCK

      [Socket]
      ListenStream=vsock::22
      Accept=yes

      [Install]
      WantedBy=sockets.target
    SYSTEMD_UNIT
  }

  ci_data[:write_files] << {
    path: '/etc/systemd/system/sshd-vsock@.service',
    permissions: '0644',
    content: <<~SYSTEMD_UNIT
      [Unit]
      Description=OpenSSH per-connection server over AF_VSOCK

      [Service]
      ExecStart=-/usr/sbin/sshd -i
      StandardInput=socket

      RuntimeDirectory=sshd
      RuntimeDirectoryMode=0755
      RuntimeDirectoryPreserve=yes
    SYSTEMD_UNIT
  }
end

vm.reset_machine!
vm.prepare_vm_files
child_pid = fork do
  STDOUT.close
  STDERR.close
  STDIN.close

  vm.vm_start_exec
  exit(1)
end

puts "QEMU PID: #{child_pid}. Waiting for qmp socket..."
start_time = Time.now.to_f
cli = nil
loop do
  socket_path = vm.qmp_socket_path
  if File.socket?(socket_path)
    cli = UNIXSocket.new(socket_path)
    break
  end
  if (Time.now.to_f - start_time) > 30.0
    puts "QEMU start timed out after 30 seconds"
    exit(1)
  end
  sleep(0.2)
end
puts "Connected to qmp."

read_messages = []
Thread.start do
  loop do
    begin
      read_messages << JSON.parse(cli.readline("\r\n", chomp: true))
    rescue EOFError
      puts "(qmp socket EOF)"

      break
    end
  end
end

cmd = JSON.dump({ execute: 'qmp_capabilities', arguments: { enable: ['oob'] } })
cli.write("#{cmd}\r\n")

ga_socket = UNIXSocket.new(vm.ga_socket_path)
loop do
  begin
    data = JSON.parse(ga_socket.readline(chomp: true))
    info = data['info']
    break if info == '--finished--'

    puts "Info from VM: #{info}"
  rescue EOFError
    puts "(guestagent socket EOF)"

    break
  end
end

sleep(2)

cmd = JSON.dump({ execute: 'quit', arguments: {} })
cli.write("#{cmd}\r\n") rescue nil

sleep(2)

puts "Done. read_messages:"
puts(read_messages)
